FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY /src .
WORKDIR "src/Radzinsky.Host"
RUN dotnet restore "Radzinsky.Host.csproj"
RUN dotnet build "Radzinsky.Host.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Radzinsky.Host.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Radzinsky.Host.dll"]
