version: "3.9"
services:
  radzinsky:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s
      timeout: 2s
      retries: 5